# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wnd1.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1130, 831)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.tree = QtWidgets.QTreeView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tree.sizePolicy().hasHeightForWidth())
        self.tree.setSizePolicy(sizePolicy)
        self.tree.setObjectName("tree")
        self.horizontalLayout_11.addWidget(self.tree)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pic_show = QtWidgets.QLabel(self.centralwidget)
        self.pic_show.setText("")
        self.pic_show.setObjectName("pic_show")
        self.verticalLayout_2.addWidget(self.pic_show)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.le_Pro = QtWidgets.QLineEdit(self.groupBox)
        self.le_Pro.setObjectName("le_Pro")
        self.horizontalLayout.addWidget(self.le_Pro)
        self.horizontalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.le_Pic_path = QtWidgets.QLineEdit(self.groupBox)
        self.le_Pic_path.setObjectName("le_Pic_path")
        self.horizontalLayout_2.addWidget(self.le_Pic_path)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.le_Save_path = QtWidgets.QLineEdit(self.groupBox)
        self.le_Save_path.setObjectName("le_Save_path")
        self.horizontalLayout_3.addWidget(self.le_Save_path)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.le_Video_path = QtWidgets.QLineEdit(self.groupBox)
        self.le_Video_path.setObjectName("le_Video_path")
        self.horizontalLayout_4.addWidget(self.le_Video_path)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.le_module_path = QtWidgets.QLineEdit(self.groupBox)
        self.le_module_path.setObjectName("le_module_path")
        self.horizontalLayout_5.addWidget(self.le_module_path)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.rb_pic = QtWidgets.QRadioButton(self.groupBox)
        self.rb_pic.setObjectName("rb_pic")
        self.horizontalLayout_8.addWidget(self.rb_pic)
        self.rb_video = QtWidgets.QRadioButton(self.groupBox)
        self.rb_video.setObjectName("rb_video")
        self.horizontalLayout_8.addWidget(self.rb_video)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_8)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_10.addLayout(self.verticalLayout_2)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_11)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1130, 28))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.new_pro = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/res/xinjian.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.new_pro.setIcon(icon)
        self.new_pro.setObjectName("new_pro")
        self.open_pro = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ico/res/open.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_pro.setIcon(icon1)
        self.open_pro.setObjectName("open_pro")
        self.save_pro = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ico/res/save.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_pro.setIcon(icon2)
        self.save_pro.setObjectName("save_pro")
        self.saveas_pro = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/ico/res/save_as.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveas_pro.setIcon(icon3)
        self.saveas_pro.setObjectName("saveas_pro")
        self.set_pic_path = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/ico/res/peizhi2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.set_pic_path.setIcon(icon4)
        self.set_pic_path.setObjectName("set_pic_path")
        self.save_results_path = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/ico/res/peizhi1.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_results_path.setIcon(icon5)
        self.save_results_path.setObjectName("save_results_path")
        self.read_module = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/ico/res/read_h5.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.read_module.setIcon(icon6)
        self.read_module.setObjectName("read_module")
        self.open_results_path = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/ico/res/open_results.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_results_path.setIcon(icon7)
        self.open_results_path.setObjectName("open_results_path")
        self.start_detect = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/ico/res/detect.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.start_detect.setIcon(icon8)
        self.start_detect.setObjectName("start_detect")
        self.set_video_path = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/ico/res/video.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.set_video_path.setIcon(icon9)
        self.set_video_path.setObjectName("set_video_path")
        self.menu.addAction(self.new_pro)
        self.menu.addAction(self.open_pro)
        self.menu.addAction(self.save_pro)
        self.menu.addAction(self.saveas_pro)
        self.menu_2.addAction(self.set_pic_path)
        self.menu_2.addAction(self.save_results_path)
        self.menu_2.addAction(self.set_video_path)
        self.menu_2.addAction(self.read_module)
        self.menu_3.addAction(self.open_results_path)
        self.menu_3.addAction(self.start_detect)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "配置信息:"))
        self.label.setText(_translate("MainWindow", "工程路径:"))
        self.label_2.setText(_translate("MainWindow", "检测图片路径:"))
        self.label_3.setText(_translate("MainWindow", "结果保存路径:"))
        self.label_4.setText(_translate("MainWindow", "视频源路径:"))
        self.label_5.setText(_translate("MainWindow", "模型路径:"))
        self.label_6.setText(_translate("MainWindow", "检测类型:"))
        self.rb_pic.setText(_translate("MainWindow", "图片"))
        self.rb_video.setText(_translate("MainWindow", "视频"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "配置"))
        self.menu_3.setTitle(_translate("MainWindow", "操作"))
        self.new_pro.setText(_translate("MainWindow", "创建工程"))
        self.open_pro.setText(_translate("MainWindow", "打开工程"))
        self.save_pro.setText(_translate("MainWindow", "保存工程"))
        self.saveas_pro.setText(_translate("MainWindow", "另存为工程"))
        self.set_pic_path.setText(_translate("MainWindow", "设置文件目录"))
        self.save_results_path.setText(_translate("MainWindow", "设置保存目录"))
        self.read_module.setText(_translate("MainWindow", "读取模型文件"))
        self.open_results_path.setText(_translate("MainWindow", "打开结果目录"))
        self.start_detect.setText(_translate("MainWindow", "开始检测"))
        self.set_video_path.setText(_translate("MainWindow", "设置视频源"))

import qt_ico_rc
